// === VOCABS N4 ===
// Format:
// { question, reading, meaning, chapter }
// `question` keeps the original kanji/kana, while `reading` is hiragana for the TTS grid.

const N4_VOCAB_ROWS = [
  // === PERGAULAN & PERASAAN ===
  ["Pergaulan & Perasaan", "具合", "ぐあい", "keadaan, kondisi"],
  ["Pergaulan & Perasaan", "関係", "かんけい", "hubungan"],
  ["Pergaulan & Perasaan", "気", "き", "udara, semangat, suasana"],
  ["Pergaulan & Perasaan", "気分", "きぶん", "perasaan, suasana, keadaan kesehatan"],
  ["Pergaulan & Perasaan", "気持ち", "きもち", "perasaan, suasana"],
  ["Pergaulan & Perasaan", "おかげ", "おかげ", "berkat, karena"],
  ["Pergaulan & Perasaan", "お見舞い", "おみまい", "kunjungan, menjenguk orang sakit"],
  ["Pergaulan & Perasaan", "お土産", "おみやげ", "oleh-oleh, suvenir"],
  ["Pergaulan & Perasaan", "お礼", "おれい", "hormat, terima kasih"],
  ["Pergaulan & Perasaan", "都合", "つごう", "keadaan, urusan, kenyamanan waktu"],
  ["Pergaulan & Perasaan", "案内", "あんない", "panduan, informasi"],
  ["Pergaulan & Perasaan", "安心", "あんしん", "lega, tenang"],
  ["Pergaulan & Perasaan", "安全", "あんぜん", "aman, keselamatan"],
  ["Pergaulan & Perasaan", "意見", "いけん", "pendapat"],
  ["Pergaulan & Perasaan", "嘘", "うそ", "bohong"],
  ["Pergaulan & Perasaan", "遠慮", "えんりょ", "sungkan, menahan diri"],
  ["Pergaulan & Perasaan", "お祝い", "おいわい", "perayaan, ucapan selamat"],
  ["Pergaulan & Perasaan", "贈り物", "おくりもの", "hadiah"],
  ["Pergaulan & Perasaan", "謝る", "あやまる", "meminta maaf"],
  ["Pergaulan & Perasaan", "喜ぶ", "よろこぶ", "senang, gembira"],
  ["Pergaulan & Perasaan", "泣く", "なく", "menangis"],
  ["Pergaulan & Perasaan", "笑う", "わらう", "tertawa"],
  ["Pergaulan & Perasaan", "怒る", "おこる", "marah"],
  ["Pergaulan & Perasaan", "困る", "こまる", "kesulitan, bingung"],

  // === PETA & LOKASI ===
  ["Peta & Lokasi", "場所", "ばしょ", "tempat"],
  ["Peta & Lokasi", "美術館", "びじゅつかん", "gedung kesenian, museum seni"],
  ["Peta & Lokasi", "地理", "ちり", "ilmu bumi, geografi"],
  ["Peta & Lokasi", "駐車場", "ちゅうしゃじょう", "tempat parkir"],
  ["Peta & Lokasi", "動物園", "どうぶつえん", "kebun binatang"],
  ["Peta & Lokasi", "ガソリンスタンド", "がそりんすたんど", "pompa bensin"],
  ["Peta & Lokasi", "飛行場", "ひこうじょう", "bandara, lapangan terbang"],
  ["Peta & Lokasi", "田舎", "いなか", "desa, dusun, kampung"],
  ["Peta & Lokasi", "海岸", "かいがん", "pantai, tepi laut"],
  ["Peta & Lokasi", "会場", "かいじょう", "ruang rapat, tempat pertemuan"],
  ["Peta & Lokasi", "近所", "きんじょ", "daerah sekitar"],
  ["Peta & Lokasi", "郊外", "こうがい", "luar kota"],
  ["Peta & Lokasi", "工場", "こうじょう", "pabrik"],
  ["Peta & Lokasi", "講堂", "こうどう", "aula"],
  ["Peta & Lokasi", "港", "みなと", "pelabuhan"],
  ["Peta & Lokasi", "湖", "みずうみ", "danau"],
  ["Peta & Lokasi", "寺", "てら", "kuil Buddha"],
  ["Peta & Lokasi", "神社", "じんじゃ", "kuil Shinto"],
  ["Peta & Lokasi", "交差点", "こうさてん", "perempatan, persimpangan"],
  ["Peta & Lokasi", "坂", "さか", "tanjakan, lereng"],
  ["Peta & Lokasi", "角", "かど", "sudut"],
  ["Peta & Lokasi", "道", "みち", "jalan"],
  ["Peta & Lokasi", "通り", "とおり", "jalan, lalu lintas"],
  ["Peta & Lokasi", "住所", "じゅうしょ", "alamat"],
  ["Peta & Lokasi", "場所代", "ばしょだい", "biaya tempat"],

  // === TRANSPORTASI & PERJALANAN ===
  ["Transportasi & Perjalanan", "交通", "こうつう", "lalu lintas, transportasi"],
  ["Transportasi & Perjalanan", "特急", "とっきゅう", "kereta ekspres khusus"],
  ["Transportasi & Perjalanan", "急行", "きゅうこう", "kereta ekspres"],
  ["Transportasi & Perjalanan", "普通", "ふつう", "biasa, lokal"],
  ["Transportasi & Perjalanan", "汽車", "きしゃ", "kereta api"],
  ["Transportasi & Perjalanan", "船", "ふね", "kapal"],
  ["Transportasi & Perjalanan", "空港", "くうこう", "bandara"],
  ["Transportasi & Perjalanan", "飛行機", "ひこうき", "pesawat terbang"],
  ["Transportasi & Perjalanan", "運転", "うんてん", "mengemudi"],
  ["Transportasi & Perjalanan", "運転手", "うんてんしゅ", "sopir"],
  ["Transportasi & Perjalanan", "乗り物", "のりもの", "kendaraan"],
  ["Transportasi & Perjalanan", "乗り換え", "のりかえ", "pindah kendaraan"],
  ["Transportasi & Perjalanan", "切符", "きっぷ", "tiket"],
  ["Transportasi & Perjalanan", "出発", "しゅっぱつ", "keberangkatan"],
  ["Transportasi & Perjalanan", "到着", "とうちゃく", "kedatangan"],
  ["Transportasi & Perjalanan", "旅行", "りょこう", "perjalanan, wisata"],
  ["Transportasi & Perjalanan", "旅館", "りょかん", "penginapan Jepang"],
  ["Transportasi & Perjalanan", "予約", "よやく", "reservasi"],
  ["Transportasi & Perjalanan", "見物", "けんぶつ", "tamasya, melihat-lihat"],
  ["Transportasi & Perjalanan", "見送り", "みおくり", "mengantar keberangkatan"],

  // === KEGIATAN & KOMUNIKASI ===
  ["Kegiatan & Komunikasi", "挨拶", "あいさつ", "salam, sapaan"],
  ["Kegiatan & Komunikasi", "連絡", "れんらく", "kontak, menghubungi"],
  ["Kegiatan & Komunikasi", "返事", "へんじ", "jawaban, balasan"],
  ["Kegiatan & Komunikasi", "相談", "そうだん", "konsultasi"],
  ["Kegiatan & Komunikasi", "説明", "せつめい", "penjelasan"],
  ["Kegiatan & Komunikasi", "質問", "しつもん", "pertanyaan"],
  ["Kegiatan & Komunikasi", "答え", "こたえ", "jawaban"],
  ["Kegiatan & Komunikasi", "用意", "ようい", "persiapan"],
  ["Kegiatan & Komunikasi", "準備", "じゅんび", "persiapan"],
  ["Kegiatan & Komunikasi", "練習", "れんしゅう", "latihan"],
  ["Kegiatan & Komunikasi", "予習", "よしゅう", "persiapan pelajaran"],
  ["Kegiatan & Komunikasi", "復習", "ふくしゅう", "ulangan, review pelajaran"],
  ["Kegiatan & Komunikasi", "研究", "けんきゅう", "penelitian"],
  ["Kegiatan & Komunikasi", "発音", "はつおん", "pelafalan"],
  ["Kegiatan & Komunikasi", "翻訳", "ほんやく", "terjemahan"],
  ["Kegiatan & Komunikasi", "放送", "ほうそう", "siaran"],
  ["Kegiatan & Komunikasi", "約束", "やくそく", "janji"],
  ["Kegiatan & Komunikasi", "用事", "ようじ", "urusan"],
  ["Kegiatan & Komunikasi", "会議", "かいぎ", "rapat"],
  ["Kegiatan & Komunikasi", "会話", "かいわ", "percakapan"],
  ["Kegiatan & Komunikasi", "紹介", "しょうかい", "perkenalan, pengenalan"],
  ["Kegiatan & Komunikasi", "招待", "しょうたい", "undangan"],
  ["Kegiatan & Komunikasi", "注意", "ちゅうい", "perhatian, peringatan"],
  ["Kegiatan & Komunikasi", "連れて行く", "つれていく", "membawa pergi"],
  ["Kegiatan & Komunikasi", "手伝う", "てつだう", "membantu"],

  // === BENDA & KEHIDUPAN ===
  ["Benda & Kehidupan", "石", "いし", "batu"],
  ["Benda & Kehidupan", "枝", "えだ", "ranting"],
  ["Benda & Kehidupan", "草", "くさ", "rumput"],
  ["Benda & Kehidupan", "葉", "は", "daun"],
  ["Benda & Kehidupan", "星", "ほし", "bintang"],
  ["Benda & Kehidupan", "雲", "くも", "awan"],
  ["Benda & Kehidupan", "光", "ひかり", "cahaya"],
  ["Benda & Kehidupan", "音", "おと", "bunyi, suara"],
  ["Benda & Kehidupan", "線", "せん", "garis"],
  ["Benda & Kehidupan", "表", "おもて", "depan, permukaan"],
  ["Benda & Kehidupan", "裏", "うら", "belakang, sisi balik"],
  ["Benda & Kehidupan", "袋", "ふくろ", "kantong, tas"],
  ["Benda & Kehidupan", "財布", "さいふ", "dompet"],
  ["Benda & Kehidupan", "指輪", "ゆびわ", "cincin"],
  ["Benda & Kehidupan", "人形", "にんぎょう", "boneka"],
  ["Benda & Kehidupan", "棚", "たな", "rak"],
  ["Benda & Kehidupan", "畳", "たたみ", "tatami"],
  ["Benda & Kehidupan", "布団", "ふとん", "kasur futon"],
  ["Benda & Kehidupan", "毛布", "もうふ", "selimut"],
  ["Benda & Kehidupan", "鏡", "かがみ", "cermin"],
  ["Benda & Kehidupan", "道具", "どうぐ", "alat"],
  ["Benda & Kehidupan", "機械", "きかい", "mesin"],
  ["Benda & Kehidupan", "部品", "ぶひん", "suku cadang"],
  ["Benda & Kehidupan", "材料", "ざいりょう", "bahan"],
  ["Benda & Kehidupan", "品物", "しなもの", "barang"],
  ["Benda & Kehidupan", "値段", "ねだん", "harga"],
  ["Benda & Kehidupan", "お釣り", "おつり", "uang kembalian"],
  ["Benda & Kehidupan", "売り場", "うりば", "tempat penjualan"],
  ["Benda & Kehidupan", "会計", "かいけい", "kasir, pembayaran"],
  ["Benda & Kehidupan", "包装", "ほうそう", "bungkus, kemasan"],

  // === ORANG & MASYARAKAT ===
  ["Orang & Masyarakat", "赤ちゃん", "あかちゃん", "bayi"],
  ["Orang & Masyarakat", "息子", "むすこ", "anak laki-laki"],
  ["Orang & Masyarakat", "娘", "むすめ", "anak perempuan"],
  ["Orang & Masyarakat", "祖父", "そふ", "kakek sendiri"],
  ["Orang & Masyarakat", "祖母", "そぼ", "nenek sendiri"],
  ["Orang & Masyarakat", "ご主人", "ごしゅじん", "suami orang lain"],
  ["Orang & Masyarakat", "奥さん", "おくさん", "istri orang lain"],
  ["Orang & Masyarakat", "店員", "てんいん", "pegawai toko"],
  ["Orang & Masyarakat", "係員", "かかりいん", "petugas"],
  ["Orang & Masyarakat", "看護師", "かんごし", "perawat"],
  ["Orang & Masyarakat", "警察", "けいさつ", "polisi"],
  ["Orang & Masyarakat", "泥棒", "どろぼう", "pencuri"],
  ["Orang & Masyarakat", "社長", "しゃちょう", "direktur perusahaan"],
  ["Orang & Masyarakat", "部長", "ぶちょう", "kepala bagian"],
  ["Orang & Masyarakat", "課長", "かちょう", "kepala seksi"],
  ["Orang & Masyarakat", "先輩", "せんぱい", "senior"],
  ["Orang & Masyarakat", "後輩", "こうはい", "junior"],
  ["Orang & Masyarakat", "留学生", "りゅうがくせい", "pelajar asing"],
  ["Orang & Masyarakat", "お客さん", "おきゃくさん", "tamu, pelanggan"],
  ["Orang & Masyarakat", "場合", "ばあい", "keadaan, kasus"],

  // === WAKTU & JUMLAH ===
  ["Waktu & Jumlah", "間", "あいだ", "antara, selama"],
  ["Waktu & Jumlah", "今度", "こんど", "kali ini, berikutnya"],
  ["Waktu & Jumlah", "最近", "さいきん", "akhir-akhir ini"],
  ["Waktu & Jumlah", "将来", "しょうらい", "masa depan"],
  ["Waktu & Jumlah", "昔", "むかし", "dahulu"],
  ["Waktu & Jumlah", "途中", "とちゅう", "di tengah jalan"],
  ["Waktu & Jumlah", "予定", "よてい", "rencana"],
  ["Waktu & Jumlah", "一度", "いちど", "sekali"],
  ["Waktu & Jumlah", "何度", "なんど", "berapa kali"],
  ["Waktu & Jumlah", "以内", "いない", "dalam, tidak lebih dari"],
  ["Waktu & Jumlah", "以下", "いか", "di bawah, kurang dari"],
  ["Waktu & Jumlah", "以上", "いじょう", "lebih dari, di atas"],
  ["Waktu & Jumlah", "以外", "いがい", "selain"],
  ["Waktu & Jumlah", "倍", "ばい", "kali lipat"],
  ["Waktu & Jumlah", "億", "おく", "seratus juta"],
  ["Waktu & Jumlah", "全部", "ぜんぶ", "semua"],
  ["Waktu & Jumlah", "大部分", "だいぶぶん", "sebagian besar"],
  ["Waktu & Jumlah", "十分", "じゅうぶん", "cukup"],
  ["Waktu & Jumlah", "途中", "とちゅう", "di tengah proses"],
  ["Waktu & Jumlah", "期間", "きかん", "periode"],

  // === KATA SIFAT & KETERANGAN ===
  ["Kata Sifat & Keterangan", "美しい", "うつくしい", "indah"],
  ["Kata Sifat & Keterangan", "嬉しい", "うれしい", "senang"],
  ["Kata Sifat & Keterangan", "悲しい", "かなしい", "sedih"],
  ["Kata Sifat & Keterangan", "厳しい", "きびしい", "keras, ketat"],
  ["Kata Sifat & Keterangan", "細かい", "こまかい", "kecil, rinci"],
  ["Kata Sifat & Keterangan", "怖い", "こわい", "takut, menakutkan"],
  ["Kata Sifat & Keterangan", "寂しい", "さびしい", "sepi, kesepian"],
  ["Kata Sifat & Keterangan", "素晴らしい", "すばらしい", "hebat, luar biasa"],
  ["Kata Sifat & Keterangan", "珍しい", "めずらしい", "jarang, unik"],
  ["Kata Sifat & Keterangan", "柔らかい", "やわらかい", "lunak, lembut"],
  ["Kata Sifat & Keterangan", "硬い", "かたい", "keras"],
  ["Kata Sifat & Keterangan", "浅い", "あさい", "dangkal"],
  ["Kata Sifat & Keterangan", "深い", "ふかい", "dalam"],
  ["Kata Sifat & Keterangan", "苦い", "にがい", "pahit"],
  ["Kata Sifat & Keterangan", "恥ずかしい", "はずかしい", "malu"],
  ["Kata Sifat & Keterangan", "変", "へん", "aneh"],
  ["Kata Sifat & Keterangan", "丁寧", "ていねい", "sopan, teliti"],
  ["Kata Sifat & Keterangan", "親切", "しんせつ", "baik hati"],
  ["Kata Sifat & Keterangan", "熱心", "ねっしん", "sungguh-sungguh"],
  ["Kata Sifat & Keterangan", "複雑", "ふくざつ", "rumit"],
  ["Kata Sifat & Keterangan", "簡単", "かんたん", "mudah"],
  ["Kata Sifat & Keterangan", "急", "きゅう", "mendadak, cepat"],
  ["Kata Sifat & Keterangan", "特別", "とくべつ", "khusus"],
  ["Kata Sifat & Keterangan", "必要", "ひつよう", "perlu"],
  ["Kata Sifat & Keterangan", "十分", "じゅうぶん", "cukup"],
  ["Kata Sifat & Keterangan", "はっきり", "はっきり", "jelas"],
  ["Kata Sifat & Keterangan", "すっかり", "すっかり", "sepenuhnya"],
  ["Kata Sifat & Keterangan", "しっかり", "しっかり", "dengan kuat, sungguh-sungguh"],
  ["Kata Sifat & Keterangan", "できるだけ", "できるだけ", "sebisa mungkin"],
  ["Kata Sifat & Keterangan", "必ず", "かならず", "pasti"],

  // === KATA KERJA ===
  ["Kata Kerja", "上がる", "あがる", "naik"],
  ["Kata Kerja", "集める", "あつめる", "mengumpulkan"],
  ["Kata Kerja", "選ぶ", "えらぶ", "memilih"],
  ["Kata Kerja", "折る", "おる", "melipat, mematahkan"],
  ["Kata Kerja", "片付ける", "かたづける", "membereskan"],
  ["Kata Kerja", "変える", "かえる", "mengubah"],
  ["Kata Kerja", "変わる", "かわる", "berubah"],
  ["Kata Kerja", "考える", "かんがえる", "memikirkan"],
  ["Kata Kerja", "聞こえる", "きこえる", "terdengar"],
  ["Kata Kerja", "決める", "きめる", "memutuskan"],
  ["Kata Kerja", "決まる", "きまる", "diputuskan"],
  ["Kata Kerja", "比べる", "くらべる", "membandingkan"],
  ["Kata Kerja", "暮れる", "くれる", "menjadi gelap"],
  ["Kata Kerja", "壊す", "こわす", "merusak"],
  ["Kata Kerja", "壊れる", "こわれる", "rusak"],
  ["Kata Kerja", "探す", "さがす", "mencari"],
  ["Kata Kerja", "下がる", "さがる", "turun"],
  ["Kata Kerja", "下げる", "さげる", "menurunkan"],
  ["Kata Kerja", "触る", "さわる", "menyentuh"],
  ["Kata Kerja", "調べる", "しらべる", "menyelidiki, memeriksa"],
  ["Kata Kerja", "知らせる", "しらせる", "memberi tahu"],
  ["Kata Kerja", "進む", "すすむ", "maju"],
  ["Kata Kerja", "捨てる", "すてる", "membuang"],
  ["Kata Kerja", "育てる", "そだてる", "membesarkan, merawat"],
  ["Kata Kerja", "倒れる", "たおれる", "roboh, jatuh"],
  ["Kata Kerja", "足す", "たす", "menambahkan"],
  ["Kata Kerja", "足りる", "たりる", "cukup"],
  ["Kata Kerja", "捕まえる", "つかまえる", "menangkap"],
  ["Kata Kerja", "包む", "つつむ", "membungkus"],
  ["Kata Kerja", "続く", "つづく", "berlanjut"],
  ["Kata Kerja", "続ける", "つづける", "melanjutkan"],
  ["Kata Kerja", "伝える", "つたえる", "menyampaikan"],
  ["Kata Kerja", "手伝う", "てつだう", "membantu"],
  ["Kata Kerja", "届ける", "とどける", "mengantarkan"],
  ["Kata Kerja", "直す", "なおす", "memperbaiki"],
  ["Kata Kerja", "直る", "なおる", "menjadi baik, sembuh"],
  ["Kata Kerja", "慣れる", "なれる", "terbiasa"],
  ["Kata Kerja", "逃げる", "にげる", "melarikan diri"],
  ["Kata Kerja", "塗る", "ぬる", "mengoles, mengecat"],
  ["Kata Kerja", "残る", "のこる", "tersisa"],
  ["Kata Kerja", "乗り換える", "のりかえる", "pindah kendaraan"],
  ["Kata Kerja", "運ぶ", "はこぶ", "mengangkut"],
  ["Kata Kerja", "始める", "はじめる", "memulai"],
  ["Kata Kerja", "払う", "はらう", "membayar"],
  ["Kata Kerja", "冷える", "ひえる", "menjadi dingin"],
  ["Kata Kerja", "増える", "ふえる", "bertambah"],
  ["Kata Kerja", "太る", "ふとる", "menjadi gemuk"],
  ["Kata Kerja", "褒める", "ほめる", "memuji"],
  ["Kata Kerja", "間に合う", "まにあう", "sempat, tepat waktu"],
  ["Kata Kerja", "見つかる", "みつかる", "ditemukan"],
  ["Kata Kerja", "見つける", "みつける", "menemukan"],
  ["Kata Kerja", "戻る", "もどる", "kembali"],
  ["Kata Kerja", "焼く", "やく", "membakar, memanggang"],
  ["Kata Kerja", "役に立つ", "やくにたつ", "berguna"],
  ["Kata Kerja", "汚れる", "よごれる", "menjadi kotor"],
  ["Kata Kerja", "沸かす", "わかす", "mendidihkan"],
  ["Kata Kerja", "沸く", "わく", "mendidih"],
  ["Kata Kerja", "別れる", "わかれる", "berpisah"],
  ["Kata Kerja", "忘れ物", "わすれもの", "barang tertinggal"],
];

window.VOCABS = N4_VOCAB_ROWS.map(([group, question, reading, meaning]) => ({
  question,
  reading,
  meaning,
  chapter: ["N4", group],
}));
